# Generated by Django 3.2 on 2021-05-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0038_auto_20210307_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default=0, help_text='PANICIENT STATUS', max_length=10),
        ),
    ]
