# Generated by Django 3.2 on 2021-05-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0041_alter_patient_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
    ]
