# Generated by Django 3.2 on 2021-05-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0043_rename_messsage_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='image',
        ),
    ]
