# Generated by Django 3.2 on 2021-05-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0044_remove_donor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (0, 'Inactive')], default=0, help_text='DONOR STATUS', max_length=10),
        ),
    ]
